# Makefile.in generated by automake 1.15 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2014 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/btpd
pkgincludedir = $(includedir)/btpd
pkglibdir = $(libdir)/btpd
pkglibexecdir = $(libexecdir)/btpd
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = btpd/btpd$(EXEEXT) cli/btcli$(EXEEXT) \
	cli/btinfo$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
LIBRARIES = $(noinst_LIBRARIES)
AR = ar
ARFLAGS = cru
AM_V_AR = $(am__v_AR_$(V))
am__v_AR_ = $(am__v_AR_$(AM_DEFAULT_VERBOSITY))
am__v_AR_0 = @echo "  AR      " $@;
am__v_AR_1 = 
evloop_libevloop_a_AR = $(AR) $(ARFLAGS)
am__dirstamp = $(am__leading_dot)dirstamp
am_evloop_libevloop_a_OBJECTS = evloop/timeheap.$(OBJEXT) \
	evloop/timer.$(OBJEXT)
evloop_libevloop_a_OBJECTS = $(am_evloop_libevloop_a_OBJECTS)
misc_libmisc_a_AR = $(AR) $(ARFLAGS)
misc_libmisc_a_LIBADD =
am_misc_libmisc_a_OBJECTS = misc/benc.$(OBJEXT) misc/btpd_if.$(OBJEXT) \
	misc/metainfo.$(OBJEXT) misc/hashtable.$(OBJEXT) \
	misc/http_client.$(OBJEXT) misc/iobuf.$(OBJEXT) \
	misc/stream.$(OBJEXT) misc/subr.$(OBJEXT)
misc_libmisc_a_OBJECTS = $(am_misc_libmisc_a_OBJECTS)
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)"
PROGRAMS = $(bin_PROGRAMS)
am_btpd_btpd_OBJECTS = btpd/btpd_btpd-active.$(OBJEXT) \
	btpd/btpd_btpd-addrinfo.$(OBJEXT) \
	btpd/btpd_btpd-btpd.$(OBJEXT) btpd/btpd_btpd-cli_if.$(OBJEXT) \
	btpd/btpd_btpd-content.$(OBJEXT) \
	btpd/btpd_btpd-download.$(OBJEXT) \
	btpd/btpd_btpd-download_subr.$(OBJEXT) \
	btpd/btpd_btpd-http_tr_if.$(OBJEXT) \
	btpd/btpd_btpd-main.$(OBJEXT) \
	btpd/btpd_btpd-nameconn.$(OBJEXT) btpd/btpd_btpd-net.$(OBJEXT) \
	btpd/btpd_btpd-net_buf.$(OBJEXT) btpd/btpd_btpd-opts.$(OBJEXT) \
	btpd/btpd_btpd-peer.$(OBJEXT) \
	btpd/btpd_btpd-thread_cb.$(OBJEXT) \
	btpd/btpd_btpd-tlib.$(OBJEXT) btpd/btpd_btpd-torrent.$(OBJEXT) \
	btpd/btpd_btpd-tracker_req.$(OBJEXT) \
	btpd/btpd_btpd-upload.$(OBJEXT) btpd/btpd_btpd-util.$(OBJEXT)
btpd_btpd_OBJECTS = $(am_btpd_btpd_OBJECTS)
btpd_btpd_DEPENDENCIES = misc/libmisc.a evloop/libevloop.a
btpd_btpd_LINK = $(CCLD) $(btpd_btpd_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
am_cli_btcli_OBJECTS = cli/btcli.$(OBJEXT) cli/add.$(OBJEXT) \
	cli/del.$(OBJEXT) cli/list.$(OBJEXT) cli/rate.$(OBJEXT) \
	cli/kill.$(OBJEXT) cli/start.$(OBJEXT) cli/stop.$(OBJEXT) \
	cli/stat.$(OBJEXT)
cli_btcli_OBJECTS = $(am_cli_btcli_OBJECTS)
cli_btcli_DEPENDENCIES = misc/libmisc.a
am_cli_btinfo_OBJECTS = cli/btinfo.$(OBJEXT)
cli_btinfo_OBJECTS = $(am_cli_btinfo_OBJECTS)
cli_btinfo_DEPENDENCIES = misc/libmisc.a
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(evloop_libevloop_a_SOURCES) \
	$(EXTRA_evloop_libevloop_a_SOURCES) $(misc_libmisc_a_SOURCES) \
	$(btpd_btpd_SOURCES) $(cli_btcli_SOURCES) \
	$(cli_btinfo_SOURCES)
DIST_SOURCES = $(evloop_libevloop_a_SOURCES) \
	$(EXTRA_evloop_libevloop_a_SOURCES) $(misc_libmisc_a_SOURCES) \
	$(btpd_btpd_SOURCES) $(cli_btcli_SOURCES) \
	$(cli_btinfo_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
man1dir = $(mandir)/man1
NROFF = nroff
MANS = $(dist_man1_MANS)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(dist_man1_MANS) $(srcdir)/Makefile.in README \
	compile depcomp install-sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /mnt/storage/pkg/btpd/missing aclocal-1.15
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} /mnt/storage/pkg/btpd/missing autoconf
AUTOHEADER = ${SHELL} /mnt/storage/pkg/btpd/missing autoheader
AUTOMAKE = ${SHELL} /mnt/storage/pkg/btpd/missing automake-1.15
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CLOCKLIB = 
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"btpd\" -DPACKAGE_TARNAME=\"btpd\" -DPACKAGE_VERSION=\"0.16+\" -DPACKAGE_STRING=\"btpd\ 0.16+\" -DPACKAGE_BUGREPORT=\"btpd-users@googlegroups.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"btpd\" -DVERSION=\"0.16+\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_ASPRINTF=1 -DHAVE_CLOCK_MONOTONIC=1
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EVLOOP_IMPL = evloop/epoll.o
EVLOOP_METHOD = EVLOOP_EPOLL
EXEEXT = 
GREP = /usr/bin/grep
INETLIBS = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /mnt/storage/pkg/btpd/missing makeinfo
MKDIR_P = /usr/bin/mkdir -p
OBJEXT = o
PACKAGE = btpd
PACKAGE_BUGREPORT = btpd-users@googlegroups.com
PACKAGE_NAME = btpd
PACKAGE_STRING = btpd 0.16+
PACKAGE_TARNAME = btpd
PACKAGE_URL = 
PACKAGE_VERSION = 0.16+
PATH_SEPARATOR = :
RANLIB = ranlib
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
TD_CFLAGS = -pthread
TD_LIBS = 
VERSION = 0.16+
WARNNPS = -Wno-pointer-sign
abs_builddir = /mnt/storage/pkg/btpd
abs_srcdir = /mnt/storage/pkg/btpd
abs_top_builddir = /mnt/storage/pkg/btpd
abs_top_srcdir = /mnt/storage/pkg/btpd
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /mnt/storage/pkg/btpd/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
openssl_CPPFLAGS = 
openssl_LDFLAGS = 
pdfdir = ${docdir}
prefix = /usr
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AM_CFLAGS = -std=c99 -Wall -Wno-pointer-sign
AM_CPPFLAGS = -D_FILE_OFFSET_BITS=64 -DEVLOOP_EPOLL -I$(top_srcdir)/misc -I$(top_srcdir)/evloop 
AM_LDFLAGS = 
noinst_LIBRARIES = misc/libmisc.a evloop/libevloop.a
dist_man1_MANS = doc/btcli.1 doc/btinfo.1 doc/btpd.1
EXTRA_DIST = COPYRIGHT CHANGES

# btpd
btpd_btpd_SOURCES = \
	btpd/active.c btpd/active.h btpd/addrinfo.c\
	btpd/btpd.c btpd/btpd.h\
	btpd/cli_if.c btpd/content.c btpd/content.h\
	btpd/download.c btpd/download_subr.c btpd/download.h\
	btpd/http_tr_if.c\
	btpd/main.c\
	btpd/nameconn.c btpd/net.c btpd/net.h btpd/net_types.h\
	btpd/net_buf.c btpd/net_buf.h\
	btpd/opts.c btpd/opts.h\
	btpd/peer.c btpd/peer.h\
	btpd/thread_cb.c btpd/tlib.c btpd/tlib.h btpd/torrent.c btpd/torrent.h\
	btpd/tracker_req.c btpd/tracker_req.h\
	btpd/upload.c btpd/upload.h\
	btpd/util.c

btpd_btpd_CFLAGS = -pthread $(AM_CFLAGS)
btpd_btpd_LDADD =  misc/libmisc.a evloop/libevloop.a -lcrypto -lm  

# btinfo
cli_btinfo_SOURCES = cli/btinfo.c
cli_btinfo_LDADD = misc/libmisc.a -lcrypto -lm

# btcli
cli_btcli_SOURCES = cli/btcli.c cli/btcli.h cli/add.c cli/del.c cli/list.c cli/rate.c cli/kill.c cli/start.c cli/stop.c cli/stat.c
cli_btcli_LDADD = misc/libmisc.a -lcrypto -lm 

# libmisc
misc_libmisc_a_SOURCES = \
	misc/benc.c misc/benc.h\
	misc/btpd_if.c misc/btpd_if.h misc/ipcdefs.h\
	misc/metainfo.c misc/metainfo.h\
	misc/hashtable.c misc/hashtable.h\
	misc/http_client.c misc/http_client.h\
	misc/iobuf.c misc/iobuf.h\
	misc/queue.h\
	misc/stream.c misc/stream.h\
	misc/subr.c misc/subr.h\
	misc/utils.h


# evloop
EXTRA_evloop_libevloop_a_SOURCES = evloop/epoll.c evloop/kqueue.c evloop/poll.c
evloop_libevloop_a_SOURCES = \
	evloop/evloop.h\
	evloop/timeheap.c evloop/timeheap.h evloop/timer.c

evloop_libevloop_a_LIBADD = evloop/epoll.o
evloop_libevloop_a_DEPENDENCIES = evloop/epoll.o
all: all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)
evloop/$(am__dirstamp):
	@$(MKDIR_P) evloop
	@: > evloop/$(am__dirstamp)
evloop/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) evloop/$(DEPDIR)
	@: > evloop/$(DEPDIR)/$(am__dirstamp)
evloop/timeheap.$(OBJEXT): evloop/$(am__dirstamp) \
	evloop/$(DEPDIR)/$(am__dirstamp)
evloop/timer.$(OBJEXT): evloop/$(am__dirstamp) \
	evloop/$(DEPDIR)/$(am__dirstamp)
evloop/epoll.$(OBJEXT): evloop/$(am__dirstamp) \
	evloop/$(DEPDIR)/$(am__dirstamp)
evloop/kqueue.$(OBJEXT): evloop/$(am__dirstamp) \
	evloop/$(DEPDIR)/$(am__dirstamp)
evloop/poll.$(OBJEXT): evloop/$(am__dirstamp) \
	evloop/$(DEPDIR)/$(am__dirstamp)

evloop/libevloop.a: $(evloop_libevloop_a_OBJECTS) $(evloop_libevloop_a_DEPENDENCIES) $(EXTRA_evloop_libevloop_a_DEPENDENCIES) evloop/$(am__dirstamp)
	$(AM_V_at)-rm -f evloop/libevloop.a
	$(AM_V_AR)$(evloop_libevloop_a_AR) evloop/libevloop.a $(evloop_libevloop_a_OBJECTS) $(evloop_libevloop_a_LIBADD)
	$(AM_V_at)$(RANLIB) evloop/libevloop.a
misc/$(am__dirstamp):
	@$(MKDIR_P) misc
	@: > misc/$(am__dirstamp)
misc/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) misc/$(DEPDIR)
	@: > misc/$(DEPDIR)/$(am__dirstamp)
misc/benc.$(OBJEXT): misc/$(am__dirstamp) \
	misc/$(DEPDIR)/$(am__dirstamp)
misc/btpd_if.$(OBJEXT): misc/$(am__dirstamp) \
	misc/$(DEPDIR)/$(am__dirstamp)
misc/metainfo.$(OBJEXT): misc/$(am__dirstamp) \
	misc/$(DEPDIR)/$(am__dirstamp)
misc/hashtable.$(OBJEXT): misc/$(am__dirstamp) \
	misc/$(DEPDIR)/$(am__dirstamp)
misc/http_client.$(OBJEXT): misc/$(am__dirstamp) \
	misc/$(DEPDIR)/$(am__dirstamp)
misc/iobuf.$(OBJEXT): misc/$(am__dirstamp) \
	misc/$(DEPDIR)/$(am__dirstamp)
misc/stream.$(OBJEXT): misc/$(am__dirstamp) \
	misc/$(DEPDIR)/$(am__dirstamp)
misc/subr.$(OBJEXT): misc/$(am__dirstamp) \
	misc/$(DEPDIR)/$(am__dirstamp)

misc/libmisc.a: $(misc_libmisc_a_OBJECTS) $(misc_libmisc_a_DEPENDENCIES) $(EXTRA_misc_libmisc_a_DEPENDENCIES) misc/$(am__dirstamp)
	$(AM_V_at)-rm -f misc/libmisc.a
	$(AM_V_AR)$(misc_libmisc_a_AR) misc/libmisc.a $(misc_libmisc_a_OBJECTS) $(misc_libmisc_a_LIBADD)
	$(AM_V_at)$(RANLIB) misc/libmisc.a
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
btpd/$(am__dirstamp):
	@$(MKDIR_P) btpd
	@: > btpd/$(am__dirstamp)
btpd/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) btpd/$(DEPDIR)
	@: > btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-active.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-addrinfo.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-btpd.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-cli_if.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-content.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-download.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-download_subr.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-http_tr_if.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-main.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-nameconn.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-net.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-net_buf.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-opts.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-peer.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-thread_cb.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-tlib.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-torrent.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-tracker_req.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-upload.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)
btpd/btpd_btpd-util.$(OBJEXT): btpd/$(am__dirstamp) \
	btpd/$(DEPDIR)/$(am__dirstamp)

btpd/btpd$(EXEEXT): $(btpd_btpd_OBJECTS) $(btpd_btpd_DEPENDENCIES) $(EXTRA_btpd_btpd_DEPENDENCIES) btpd/$(am__dirstamp)
	@rm -f btpd/btpd$(EXEEXT)
	$(AM_V_CCLD)$(btpd_btpd_LINK) $(btpd_btpd_OBJECTS) $(btpd_btpd_LDADD) $(LIBS)
cli/$(am__dirstamp):
	@$(MKDIR_P) cli
	@: > cli/$(am__dirstamp)
cli/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) cli/$(DEPDIR)
	@: > cli/$(DEPDIR)/$(am__dirstamp)
cli/btcli.$(OBJEXT): cli/$(am__dirstamp) cli/$(DEPDIR)/$(am__dirstamp)
cli/add.$(OBJEXT): cli/$(am__dirstamp) cli/$(DEPDIR)/$(am__dirstamp)
cli/del.$(OBJEXT): cli/$(am__dirstamp) cli/$(DEPDIR)/$(am__dirstamp)
cli/list.$(OBJEXT): cli/$(am__dirstamp) cli/$(DEPDIR)/$(am__dirstamp)
cli/rate.$(OBJEXT): cli/$(am__dirstamp) cli/$(DEPDIR)/$(am__dirstamp)
cli/kill.$(OBJEXT): cli/$(am__dirstamp) cli/$(DEPDIR)/$(am__dirstamp)
cli/start.$(OBJEXT): cli/$(am__dirstamp) cli/$(DEPDIR)/$(am__dirstamp)
cli/stop.$(OBJEXT): cli/$(am__dirstamp) cli/$(DEPDIR)/$(am__dirstamp)
cli/stat.$(OBJEXT): cli/$(am__dirstamp) cli/$(DEPDIR)/$(am__dirstamp)

cli/btcli$(EXEEXT): $(cli_btcli_OBJECTS) $(cli_btcli_DEPENDENCIES) $(EXTRA_cli_btcli_DEPENDENCIES) cli/$(am__dirstamp)
	@rm -f cli/btcli$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(cli_btcli_OBJECTS) $(cli_btcli_LDADD) $(LIBS)
cli/btinfo.$(OBJEXT): cli/$(am__dirstamp) \
	cli/$(DEPDIR)/$(am__dirstamp)

cli/btinfo$(EXEEXT): $(cli_btinfo_OBJECTS) $(cli_btinfo_DEPENDENCIES) $(EXTRA_cli_btinfo_DEPENDENCIES) cli/$(am__dirstamp)
	@rm -f cli/btinfo$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(cli_btinfo_OBJECTS) $(cli_btinfo_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f btpd/*.$(OBJEXT)
	-rm -f cli/*.$(OBJEXT)
	-rm -f evloop/*.$(OBJEXT)
	-rm -f misc/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include btpd/$(DEPDIR)/btpd_btpd-active.Po
include btpd/$(DEPDIR)/btpd_btpd-addrinfo.Po
include btpd/$(DEPDIR)/btpd_btpd-btpd.Po
include btpd/$(DEPDIR)/btpd_btpd-cli_if.Po
include btpd/$(DEPDIR)/btpd_btpd-content.Po
include btpd/$(DEPDIR)/btpd_btpd-download.Po
include btpd/$(DEPDIR)/btpd_btpd-download_subr.Po
include btpd/$(DEPDIR)/btpd_btpd-http_tr_if.Po
include btpd/$(DEPDIR)/btpd_btpd-main.Po
include btpd/$(DEPDIR)/btpd_btpd-nameconn.Po
include btpd/$(DEPDIR)/btpd_btpd-net.Po
include btpd/$(DEPDIR)/btpd_btpd-net_buf.Po
include btpd/$(DEPDIR)/btpd_btpd-opts.Po
include btpd/$(DEPDIR)/btpd_btpd-peer.Po
include btpd/$(DEPDIR)/btpd_btpd-thread_cb.Po
include btpd/$(DEPDIR)/btpd_btpd-tlib.Po
include btpd/$(DEPDIR)/btpd_btpd-torrent.Po
include btpd/$(DEPDIR)/btpd_btpd-tracker_req.Po
include btpd/$(DEPDIR)/btpd_btpd-upload.Po
include btpd/$(DEPDIR)/btpd_btpd-util.Po
include cli/$(DEPDIR)/add.Po
include cli/$(DEPDIR)/btcli.Po
include cli/$(DEPDIR)/btinfo.Po
include cli/$(DEPDIR)/del.Po
include cli/$(DEPDIR)/kill.Po
include cli/$(DEPDIR)/list.Po
include cli/$(DEPDIR)/rate.Po
include cli/$(DEPDIR)/start.Po
include cli/$(DEPDIR)/stat.Po
include cli/$(DEPDIR)/stop.Po
include evloop/$(DEPDIR)/epoll.Po
include evloop/$(DEPDIR)/kqueue.Po
include evloop/$(DEPDIR)/poll.Po
include evloop/$(DEPDIR)/timeheap.Po
include evloop/$(DEPDIR)/timer.Po
include misc/$(DEPDIR)/benc.Po
include misc/$(DEPDIR)/btpd_if.Po
include misc/$(DEPDIR)/hashtable.Po
include misc/$(DEPDIR)/http_client.Po
include misc/$(DEPDIR)/iobuf.Po
include misc/$(DEPDIR)/metainfo.Po
include misc/$(DEPDIR)/stream.Po
include misc/$(DEPDIR)/subr.Po

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

btpd/btpd_btpd-active.o: btpd/active.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-active.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-active.Tpo -c -o btpd/btpd_btpd-active.o `test -f 'btpd/active.c' || echo '$(srcdir)/'`btpd/active.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-active.Tpo btpd/$(DEPDIR)/btpd_btpd-active.Po
#	$(AM_V_CC)source='btpd/active.c' object='btpd/btpd_btpd-active.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-active.o `test -f 'btpd/active.c' || echo '$(srcdir)/'`btpd/active.c

btpd/btpd_btpd-active.obj: btpd/active.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-active.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-active.Tpo -c -o btpd/btpd_btpd-active.obj `if test -f 'btpd/active.c'; then $(CYGPATH_W) 'btpd/active.c'; else $(CYGPATH_W) '$(srcdir)/btpd/active.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-active.Tpo btpd/$(DEPDIR)/btpd_btpd-active.Po
#	$(AM_V_CC)source='btpd/active.c' object='btpd/btpd_btpd-active.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-active.obj `if test -f 'btpd/active.c'; then $(CYGPATH_W) 'btpd/active.c'; else $(CYGPATH_W) '$(srcdir)/btpd/active.c'; fi`

btpd/btpd_btpd-addrinfo.o: btpd/addrinfo.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-addrinfo.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-addrinfo.Tpo -c -o btpd/btpd_btpd-addrinfo.o `test -f 'btpd/addrinfo.c' || echo '$(srcdir)/'`btpd/addrinfo.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-addrinfo.Tpo btpd/$(DEPDIR)/btpd_btpd-addrinfo.Po
#	$(AM_V_CC)source='btpd/addrinfo.c' object='btpd/btpd_btpd-addrinfo.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-addrinfo.o `test -f 'btpd/addrinfo.c' || echo '$(srcdir)/'`btpd/addrinfo.c

btpd/btpd_btpd-addrinfo.obj: btpd/addrinfo.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-addrinfo.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-addrinfo.Tpo -c -o btpd/btpd_btpd-addrinfo.obj `if test -f 'btpd/addrinfo.c'; then $(CYGPATH_W) 'btpd/addrinfo.c'; else $(CYGPATH_W) '$(srcdir)/btpd/addrinfo.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-addrinfo.Tpo btpd/$(DEPDIR)/btpd_btpd-addrinfo.Po
#	$(AM_V_CC)source='btpd/addrinfo.c' object='btpd/btpd_btpd-addrinfo.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-addrinfo.obj `if test -f 'btpd/addrinfo.c'; then $(CYGPATH_W) 'btpd/addrinfo.c'; else $(CYGPATH_W) '$(srcdir)/btpd/addrinfo.c'; fi`

btpd/btpd_btpd-btpd.o: btpd/btpd.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-btpd.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-btpd.Tpo -c -o btpd/btpd_btpd-btpd.o `test -f 'btpd/btpd.c' || echo '$(srcdir)/'`btpd/btpd.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-btpd.Tpo btpd/$(DEPDIR)/btpd_btpd-btpd.Po
#	$(AM_V_CC)source='btpd/btpd.c' object='btpd/btpd_btpd-btpd.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-btpd.o `test -f 'btpd/btpd.c' || echo '$(srcdir)/'`btpd/btpd.c

btpd/btpd_btpd-btpd.obj: btpd/btpd.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-btpd.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-btpd.Tpo -c -o btpd/btpd_btpd-btpd.obj `if test -f 'btpd/btpd.c'; then $(CYGPATH_W) 'btpd/btpd.c'; else $(CYGPATH_W) '$(srcdir)/btpd/btpd.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-btpd.Tpo btpd/$(DEPDIR)/btpd_btpd-btpd.Po
#	$(AM_V_CC)source='btpd/btpd.c' object='btpd/btpd_btpd-btpd.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-btpd.obj `if test -f 'btpd/btpd.c'; then $(CYGPATH_W) 'btpd/btpd.c'; else $(CYGPATH_W) '$(srcdir)/btpd/btpd.c'; fi`

btpd/btpd_btpd-cli_if.o: btpd/cli_if.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-cli_if.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-cli_if.Tpo -c -o btpd/btpd_btpd-cli_if.o `test -f 'btpd/cli_if.c' || echo '$(srcdir)/'`btpd/cli_if.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-cli_if.Tpo btpd/$(DEPDIR)/btpd_btpd-cli_if.Po
#	$(AM_V_CC)source='btpd/cli_if.c' object='btpd/btpd_btpd-cli_if.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-cli_if.o `test -f 'btpd/cli_if.c' || echo '$(srcdir)/'`btpd/cli_if.c

btpd/btpd_btpd-cli_if.obj: btpd/cli_if.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-cli_if.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-cli_if.Tpo -c -o btpd/btpd_btpd-cli_if.obj `if test -f 'btpd/cli_if.c'; then $(CYGPATH_W) 'btpd/cli_if.c'; else $(CYGPATH_W) '$(srcdir)/btpd/cli_if.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-cli_if.Tpo btpd/$(DEPDIR)/btpd_btpd-cli_if.Po
#	$(AM_V_CC)source='btpd/cli_if.c' object='btpd/btpd_btpd-cli_if.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-cli_if.obj `if test -f 'btpd/cli_if.c'; then $(CYGPATH_W) 'btpd/cli_if.c'; else $(CYGPATH_W) '$(srcdir)/btpd/cli_if.c'; fi`

btpd/btpd_btpd-content.o: btpd/content.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-content.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-content.Tpo -c -o btpd/btpd_btpd-content.o `test -f 'btpd/content.c' || echo '$(srcdir)/'`btpd/content.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-content.Tpo btpd/$(DEPDIR)/btpd_btpd-content.Po
#	$(AM_V_CC)source='btpd/content.c' object='btpd/btpd_btpd-content.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-content.o `test -f 'btpd/content.c' || echo '$(srcdir)/'`btpd/content.c

btpd/btpd_btpd-content.obj: btpd/content.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-content.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-content.Tpo -c -o btpd/btpd_btpd-content.obj `if test -f 'btpd/content.c'; then $(CYGPATH_W) 'btpd/content.c'; else $(CYGPATH_W) '$(srcdir)/btpd/content.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-content.Tpo btpd/$(DEPDIR)/btpd_btpd-content.Po
#	$(AM_V_CC)source='btpd/content.c' object='btpd/btpd_btpd-content.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-content.obj `if test -f 'btpd/content.c'; then $(CYGPATH_W) 'btpd/content.c'; else $(CYGPATH_W) '$(srcdir)/btpd/content.c'; fi`

btpd/btpd_btpd-download.o: btpd/download.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-download.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-download.Tpo -c -o btpd/btpd_btpd-download.o `test -f 'btpd/download.c' || echo '$(srcdir)/'`btpd/download.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-download.Tpo btpd/$(DEPDIR)/btpd_btpd-download.Po
#	$(AM_V_CC)source='btpd/download.c' object='btpd/btpd_btpd-download.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-download.o `test -f 'btpd/download.c' || echo '$(srcdir)/'`btpd/download.c

btpd/btpd_btpd-download.obj: btpd/download.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-download.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-download.Tpo -c -o btpd/btpd_btpd-download.obj `if test -f 'btpd/download.c'; then $(CYGPATH_W) 'btpd/download.c'; else $(CYGPATH_W) '$(srcdir)/btpd/download.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-download.Tpo btpd/$(DEPDIR)/btpd_btpd-download.Po
#	$(AM_V_CC)source='btpd/download.c' object='btpd/btpd_btpd-download.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-download.obj `if test -f 'btpd/download.c'; then $(CYGPATH_W) 'btpd/download.c'; else $(CYGPATH_W) '$(srcdir)/btpd/download.c'; fi`

btpd/btpd_btpd-download_subr.o: btpd/download_subr.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-download_subr.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-download_subr.Tpo -c -o btpd/btpd_btpd-download_subr.o `test -f 'btpd/download_subr.c' || echo '$(srcdir)/'`btpd/download_subr.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-download_subr.Tpo btpd/$(DEPDIR)/btpd_btpd-download_subr.Po
#	$(AM_V_CC)source='btpd/download_subr.c' object='btpd/btpd_btpd-download_subr.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-download_subr.o `test -f 'btpd/download_subr.c' || echo '$(srcdir)/'`btpd/download_subr.c

btpd/btpd_btpd-download_subr.obj: btpd/download_subr.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-download_subr.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-download_subr.Tpo -c -o btpd/btpd_btpd-download_subr.obj `if test -f 'btpd/download_subr.c'; then $(CYGPATH_W) 'btpd/download_subr.c'; else $(CYGPATH_W) '$(srcdir)/btpd/download_subr.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-download_subr.Tpo btpd/$(DEPDIR)/btpd_btpd-download_subr.Po
#	$(AM_V_CC)source='btpd/download_subr.c' object='btpd/btpd_btpd-download_subr.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-download_subr.obj `if test -f 'btpd/download_subr.c'; then $(CYGPATH_W) 'btpd/download_subr.c'; else $(CYGPATH_W) '$(srcdir)/btpd/download_subr.c'; fi`

btpd/btpd_btpd-http_tr_if.o: btpd/http_tr_if.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-http_tr_if.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-http_tr_if.Tpo -c -o btpd/btpd_btpd-http_tr_if.o `test -f 'btpd/http_tr_if.c' || echo '$(srcdir)/'`btpd/http_tr_if.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-http_tr_if.Tpo btpd/$(DEPDIR)/btpd_btpd-http_tr_if.Po
#	$(AM_V_CC)source='btpd/http_tr_if.c' object='btpd/btpd_btpd-http_tr_if.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-http_tr_if.o `test -f 'btpd/http_tr_if.c' || echo '$(srcdir)/'`btpd/http_tr_if.c

btpd/btpd_btpd-http_tr_if.obj: btpd/http_tr_if.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-http_tr_if.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-http_tr_if.Tpo -c -o btpd/btpd_btpd-http_tr_if.obj `if test -f 'btpd/http_tr_if.c'; then $(CYGPATH_W) 'btpd/http_tr_if.c'; else $(CYGPATH_W) '$(srcdir)/btpd/http_tr_if.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-http_tr_if.Tpo btpd/$(DEPDIR)/btpd_btpd-http_tr_if.Po
#	$(AM_V_CC)source='btpd/http_tr_if.c' object='btpd/btpd_btpd-http_tr_if.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-http_tr_if.obj `if test -f 'btpd/http_tr_if.c'; then $(CYGPATH_W) 'btpd/http_tr_if.c'; else $(CYGPATH_W) '$(srcdir)/btpd/http_tr_if.c'; fi`

btpd/btpd_btpd-main.o: btpd/main.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-main.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-main.Tpo -c -o btpd/btpd_btpd-main.o `test -f 'btpd/main.c' || echo '$(srcdir)/'`btpd/main.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-main.Tpo btpd/$(DEPDIR)/btpd_btpd-main.Po
#	$(AM_V_CC)source='btpd/main.c' object='btpd/btpd_btpd-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-main.o `test -f 'btpd/main.c' || echo '$(srcdir)/'`btpd/main.c

btpd/btpd_btpd-main.obj: btpd/main.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-main.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-main.Tpo -c -o btpd/btpd_btpd-main.obj `if test -f 'btpd/main.c'; then $(CYGPATH_W) 'btpd/main.c'; else $(CYGPATH_W) '$(srcdir)/btpd/main.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-main.Tpo btpd/$(DEPDIR)/btpd_btpd-main.Po
#	$(AM_V_CC)source='btpd/main.c' object='btpd/btpd_btpd-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-main.obj `if test -f 'btpd/main.c'; then $(CYGPATH_W) 'btpd/main.c'; else $(CYGPATH_W) '$(srcdir)/btpd/main.c'; fi`

btpd/btpd_btpd-nameconn.o: btpd/nameconn.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-nameconn.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-nameconn.Tpo -c -o btpd/btpd_btpd-nameconn.o `test -f 'btpd/nameconn.c' || echo '$(srcdir)/'`btpd/nameconn.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-nameconn.Tpo btpd/$(DEPDIR)/btpd_btpd-nameconn.Po
#	$(AM_V_CC)source='btpd/nameconn.c' object='btpd/btpd_btpd-nameconn.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-nameconn.o `test -f 'btpd/nameconn.c' || echo '$(srcdir)/'`btpd/nameconn.c

btpd/btpd_btpd-nameconn.obj: btpd/nameconn.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-nameconn.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-nameconn.Tpo -c -o btpd/btpd_btpd-nameconn.obj `if test -f 'btpd/nameconn.c'; then $(CYGPATH_W) 'btpd/nameconn.c'; else $(CYGPATH_W) '$(srcdir)/btpd/nameconn.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-nameconn.Tpo btpd/$(DEPDIR)/btpd_btpd-nameconn.Po
#	$(AM_V_CC)source='btpd/nameconn.c' object='btpd/btpd_btpd-nameconn.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-nameconn.obj `if test -f 'btpd/nameconn.c'; then $(CYGPATH_W) 'btpd/nameconn.c'; else $(CYGPATH_W) '$(srcdir)/btpd/nameconn.c'; fi`

btpd/btpd_btpd-net.o: btpd/net.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-net.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-net.Tpo -c -o btpd/btpd_btpd-net.o `test -f 'btpd/net.c' || echo '$(srcdir)/'`btpd/net.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-net.Tpo btpd/$(DEPDIR)/btpd_btpd-net.Po
#	$(AM_V_CC)source='btpd/net.c' object='btpd/btpd_btpd-net.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-net.o `test -f 'btpd/net.c' || echo '$(srcdir)/'`btpd/net.c

btpd/btpd_btpd-net.obj: btpd/net.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-net.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-net.Tpo -c -o btpd/btpd_btpd-net.obj `if test -f 'btpd/net.c'; then $(CYGPATH_W) 'btpd/net.c'; else $(CYGPATH_W) '$(srcdir)/btpd/net.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-net.Tpo btpd/$(DEPDIR)/btpd_btpd-net.Po
#	$(AM_V_CC)source='btpd/net.c' object='btpd/btpd_btpd-net.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-net.obj `if test -f 'btpd/net.c'; then $(CYGPATH_W) 'btpd/net.c'; else $(CYGPATH_W) '$(srcdir)/btpd/net.c'; fi`

btpd/btpd_btpd-net_buf.o: btpd/net_buf.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-net_buf.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-net_buf.Tpo -c -o btpd/btpd_btpd-net_buf.o `test -f 'btpd/net_buf.c' || echo '$(srcdir)/'`btpd/net_buf.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-net_buf.Tpo btpd/$(DEPDIR)/btpd_btpd-net_buf.Po
#	$(AM_V_CC)source='btpd/net_buf.c' object='btpd/btpd_btpd-net_buf.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-net_buf.o `test -f 'btpd/net_buf.c' || echo '$(srcdir)/'`btpd/net_buf.c

btpd/btpd_btpd-net_buf.obj: btpd/net_buf.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-net_buf.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-net_buf.Tpo -c -o btpd/btpd_btpd-net_buf.obj `if test -f 'btpd/net_buf.c'; then $(CYGPATH_W) 'btpd/net_buf.c'; else $(CYGPATH_W) '$(srcdir)/btpd/net_buf.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-net_buf.Tpo btpd/$(DEPDIR)/btpd_btpd-net_buf.Po
#	$(AM_V_CC)source='btpd/net_buf.c' object='btpd/btpd_btpd-net_buf.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-net_buf.obj `if test -f 'btpd/net_buf.c'; then $(CYGPATH_W) 'btpd/net_buf.c'; else $(CYGPATH_W) '$(srcdir)/btpd/net_buf.c'; fi`

btpd/btpd_btpd-opts.o: btpd/opts.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-opts.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-opts.Tpo -c -o btpd/btpd_btpd-opts.o `test -f 'btpd/opts.c' || echo '$(srcdir)/'`btpd/opts.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-opts.Tpo btpd/$(DEPDIR)/btpd_btpd-opts.Po
#	$(AM_V_CC)source='btpd/opts.c' object='btpd/btpd_btpd-opts.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-opts.o `test -f 'btpd/opts.c' || echo '$(srcdir)/'`btpd/opts.c

btpd/btpd_btpd-opts.obj: btpd/opts.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-opts.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-opts.Tpo -c -o btpd/btpd_btpd-opts.obj `if test -f 'btpd/opts.c'; then $(CYGPATH_W) 'btpd/opts.c'; else $(CYGPATH_W) '$(srcdir)/btpd/opts.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-opts.Tpo btpd/$(DEPDIR)/btpd_btpd-opts.Po
#	$(AM_V_CC)source='btpd/opts.c' object='btpd/btpd_btpd-opts.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-opts.obj `if test -f 'btpd/opts.c'; then $(CYGPATH_W) 'btpd/opts.c'; else $(CYGPATH_W) '$(srcdir)/btpd/opts.c'; fi`

btpd/btpd_btpd-peer.o: btpd/peer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-peer.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-peer.Tpo -c -o btpd/btpd_btpd-peer.o `test -f 'btpd/peer.c' || echo '$(srcdir)/'`btpd/peer.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-peer.Tpo btpd/$(DEPDIR)/btpd_btpd-peer.Po
#	$(AM_V_CC)source='btpd/peer.c' object='btpd/btpd_btpd-peer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-peer.o `test -f 'btpd/peer.c' || echo '$(srcdir)/'`btpd/peer.c

btpd/btpd_btpd-peer.obj: btpd/peer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-peer.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-peer.Tpo -c -o btpd/btpd_btpd-peer.obj `if test -f 'btpd/peer.c'; then $(CYGPATH_W) 'btpd/peer.c'; else $(CYGPATH_W) '$(srcdir)/btpd/peer.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-peer.Tpo btpd/$(DEPDIR)/btpd_btpd-peer.Po
#	$(AM_V_CC)source='btpd/peer.c' object='btpd/btpd_btpd-peer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-peer.obj `if test -f 'btpd/peer.c'; then $(CYGPATH_W) 'btpd/peer.c'; else $(CYGPATH_W) '$(srcdir)/btpd/peer.c'; fi`

btpd/btpd_btpd-thread_cb.o: btpd/thread_cb.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-thread_cb.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-thread_cb.Tpo -c -o btpd/btpd_btpd-thread_cb.o `test -f 'btpd/thread_cb.c' || echo '$(srcdir)/'`btpd/thread_cb.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-thread_cb.Tpo btpd/$(DEPDIR)/btpd_btpd-thread_cb.Po
#	$(AM_V_CC)source='btpd/thread_cb.c' object='btpd/btpd_btpd-thread_cb.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-thread_cb.o `test -f 'btpd/thread_cb.c' || echo '$(srcdir)/'`btpd/thread_cb.c

btpd/btpd_btpd-thread_cb.obj: btpd/thread_cb.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-thread_cb.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-thread_cb.Tpo -c -o btpd/btpd_btpd-thread_cb.obj `if test -f 'btpd/thread_cb.c'; then $(CYGPATH_W) 'btpd/thread_cb.c'; else $(CYGPATH_W) '$(srcdir)/btpd/thread_cb.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-thread_cb.Tpo btpd/$(DEPDIR)/btpd_btpd-thread_cb.Po
#	$(AM_V_CC)source='btpd/thread_cb.c' object='btpd/btpd_btpd-thread_cb.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-thread_cb.obj `if test -f 'btpd/thread_cb.c'; then $(CYGPATH_W) 'btpd/thread_cb.c'; else $(CYGPATH_W) '$(srcdir)/btpd/thread_cb.c'; fi`

btpd/btpd_btpd-tlib.o: btpd/tlib.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-tlib.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-tlib.Tpo -c -o btpd/btpd_btpd-tlib.o `test -f 'btpd/tlib.c' || echo '$(srcdir)/'`btpd/tlib.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-tlib.Tpo btpd/$(DEPDIR)/btpd_btpd-tlib.Po
#	$(AM_V_CC)source='btpd/tlib.c' object='btpd/btpd_btpd-tlib.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-tlib.o `test -f 'btpd/tlib.c' || echo '$(srcdir)/'`btpd/tlib.c

btpd/btpd_btpd-tlib.obj: btpd/tlib.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-tlib.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-tlib.Tpo -c -o btpd/btpd_btpd-tlib.obj `if test -f 'btpd/tlib.c'; then $(CYGPATH_W) 'btpd/tlib.c'; else $(CYGPATH_W) '$(srcdir)/btpd/tlib.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-tlib.Tpo btpd/$(DEPDIR)/btpd_btpd-tlib.Po
#	$(AM_V_CC)source='btpd/tlib.c' object='btpd/btpd_btpd-tlib.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-tlib.obj `if test -f 'btpd/tlib.c'; then $(CYGPATH_W) 'btpd/tlib.c'; else $(CYGPATH_W) '$(srcdir)/btpd/tlib.c'; fi`

btpd/btpd_btpd-torrent.o: btpd/torrent.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-torrent.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-torrent.Tpo -c -o btpd/btpd_btpd-torrent.o `test -f 'btpd/torrent.c' || echo '$(srcdir)/'`btpd/torrent.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-torrent.Tpo btpd/$(DEPDIR)/btpd_btpd-torrent.Po
#	$(AM_V_CC)source='btpd/torrent.c' object='btpd/btpd_btpd-torrent.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-torrent.o `test -f 'btpd/torrent.c' || echo '$(srcdir)/'`btpd/torrent.c

btpd/btpd_btpd-torrent.obj: btpd/torrent.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-torrent.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-torrent.Tpo -c -o btpd/btpd_btpd-torrent.obj `if test -f 'btpd/torrent.c'; then $(CYGPATH_W) 'btpd/torrent.c'; else $(CYGPATH_W) '$(srcdir)/btpd/torrent.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-torrent.Tpo btpd/$(DEPDIR)/btpd_btpd-torrent.Po
#	$(AM_V_CC)source='btpd/torrent.c' object='btpd/btpd_btpd-torrent.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-torrent.obj `if test -f 'btpd/torrent.c'; then $(CYGPATH_W) 'btpd/torrent.c'; else $(CYGPATH_W) '$(srcdir)/btpd/torrent.c'; fi`

btpd/btpd_btpd-tracker_req.o: btpd/tracker_req.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-tracker_req.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-tracker_req.Tpo -c -o btpd/btpd_btpd-tracker_req.o `test -f 'btpd/tracker_req.c' || echo '$(srcdir)/'`btpd/tracker_req.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-tracker_req.Tpo btpd/$(DEPDIR)/btpd_btpd-tracker_req.Po
#	$(AM_V_CC)source='btpd/tracker_req.c' object='btpd/btpd_btpd-tracker_req.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-tracker_req.o `test -f 'btpd/tracker_req.c' || echo '$(srcdir)/'`btpd/tracker_req.c

btpd/btpd_btpd-tracker_req.obj: btpd/tracker_req.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-tracker_req.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-tracker_req.Tpo -c -o btpd/btpd_btpd-tracker_req.obj `if test -f 'btpd/tracker_req.c'; then $(CYGPATH_W) 'btpd/tracker_req.c'; else $(CYGPATH_W) '$(srcdir)/btpd/tracker_req.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-tracker_req.Tpo btpd/$(DEPDIR)/btpd_btpd-tracker_req.Po
#	$(AM_V_CC)source='btpd/tracker_req.c' object='btpd/btpd_btpd-tracker_req.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-tracker_req.obj `if test -f 'btpd/tracker_req.c'; then $(CYGPATH_W) 'btpd/tracker_req.c'; else $(CYGPATH_W) '$(srcdir)/btpd/tracker_req.c'; fi`

btpd/btpd_btpd-upload.o: btpd/upload.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-upload.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-upload.Tpo -c -o btpd/btpd_btpd-upload.o `test -f 'btpd/upload.c' || echo '$(srcdir)/'`btpd/upload.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-upload.Tpo btpd/$(DEPDIR)/btpd_btpd-upload.Po
#	$(AM_V_CC)source='btpd/upload.c' object='btpd/btpd_btpd-upload.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-upload.o `test -f 'btpd/upload.c' || echo '$(srcdir)/'`btpd/upload.c

btpd/btpd_btpd-upload.obj: btpd/upload.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-upload.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-upload.Tpo -c -o btpd/btpd_btpd-upload.obj `if test -f 'btpd/upload.c'; then $(CYGPATH_W) 'btpd/upload.c'; else $(CYGPATH_W) '$(srcdir)/btpd/upload.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-upload.Tpo btpd/$(DEPDIR)/btpd_btpd-upload.Po
#	$(AM_V_CC)source='btpd/upload.c' object='btpd/btpd_btpd-upload.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-upload.obj `if test -f 'btpd/upload.c'; then $(CYGPATH_W) 'btpd/upload.c'; else $(CYGPATH_W) '$(srcdir)/btpd/upload.c'; fi`

btpd/btpd_btpd-util.o: btpd/util.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-util.o -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-util.Tpo -c -o btpd/btpd_btpd-util.o `test -f 'btpd/util.c' || echo '$(srcdir)/'`btpd/util.c
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-util.Tpo btpd/$(DEPDIR)/btpd_btpd-util.Po
#	$(AM_V_CC)source='btpd/util.c' object='btpd/btpd_btpd-util.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-util.o `test -f 'btpd/util.c' || echo '$(srcdir)/'`btpd/util.c

btpd/btpd_btpd-util.obj: btpd/util.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -MT btpd/btpd_btpd-util.obj -MD -MP -MF btpd/$(DEPDIR)/btpd_btpd-util.Tpo -c -o btpd/btpd_btpd-util.obj `if test -f 'btpd/util.c'; then $(CYGPATH_W) 'btpd/util.c'; else $(CYGPATH_W) '$(srcdir)/btpd/util.c'; fi`
	$(AM_V_at)$(am__mv) btpd/$(DEPDIR)/btpd_btpd-util.Tpo btpd/$(DEPDIR)/btpd_btpd-util.Po
#	$(AM_V_CC)source='btpd/util.c' object='btpd/btpd_btpd-util.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(btpd_btpd_CFLAGS) $(CFLAGS) -c -o btpd/btpd_btpd-util.obj `if test -f 'btpd/util.c'; then $(CYGPATH_W) 'btpd/util.c'; else $(CYGPATH_W) '$(srcdir)/btpd/util.c'; fi`
install-man1: $(dist_man1_MANS)
	@$(NORMAL_INSTALL)
	@list1='$(dist_man1_MANS)'; \
	list2=''; \
	test -n "$(man1dir)" \
	  && test -n "`echo $$list1$$list2`" \
	  || exit 0; \
	echo " $(MKDIR_P) '$(DESTDIR)$(man1dir)'"; \
	$(MKDIR_P) "$(DESTDIR)$(man1dir)" || exit 1; \
	{ for i in $$list1; do echo "$$i"; done;  \
	if test -n "$$list2"; then \
	  for i in $$list2; do echo "$$i"; done \
	    | sed -n '/\.1[a-z]*$$/p'; \
	fi; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man1dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man1dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man1dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man1dir)" || exit $$?; }; \
	done; }

uninstall-man1:
	@$(NORMAL_UNINSTALL)
	@list='$(dist_man1_MANS)'; test -n "$(man1dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
	dir='$(DESTDIR)$(man1dir)'; $(am__uninstall_files_from_dir)

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(LIBRARIES) $(PROGRAMS) $(MANS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f btpd/$(DEPDIR)/$(am__dirstamp)
	-rm -f btpd/$(am__dirstamp)
	-rm -f cli/$(DEPDIR)/$(am__dirstamp)
	-rm -f cli/$(am__dirstamp)
	-rm -f evloop/$(DEPDIR)/$(am__dirstamp)
	-rm -f evloop/$(am__dirstamp)
	-rm -f misc/$(DEPDIR)/$(am__dirstamp)
	-rm -f misc/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-noinstLIBRARIES \
	mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf btpd/$(DEPDIR) cli/$(DEPDIR) evloop/$(DEPDIR) misc/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-man

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man: install-man1

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf btpd/$(DEPDIR) cli/$(DEPDIR) evloop/$(DEPDIR) misc/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-man

uninstall-man: uninstall-man1

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic \
	clean-noinstLIBRARIES cscope cscopelist-am ctags ctags-am dist \
	dist-all dist-bzip2 dist-gzip dist-lzip dist-shar dist-tarZ \
	dist-xz dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-man1 install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS uninstall-man \
	uninstall-man1

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
